# Docker compose for OLS-Solution
# result under: cat /tmp/codeBase/ols_solution/result/ols_result.txt
# run with --> docker compose -f .\docker-compose.ols.yml up

version: "3.8"

services:
  knowledgeBase:
    image: gerhard1132/knowledgebase-gradepredictor:latest
    volumes:
      - ai_system:/tmp
    command: 
      - sh
      - "-c"
      - |
        rm -rf /tmp/knowledgeBase/ && cp -r /knowledgeBase/ /tmp/;

  activationBase:
      image: gerhard1132/activationbase-gradepredictor
      volumes:
        - ai_system:/tmp
      command: 
      - sh
      - "-c"
      - |
        rm -rf /tmp/activationBase/ && cp -r /activationBase/ /tmp/;

  codeBase:
    image: gerhard1132/codebase-gradepredictor:latest
    volumes:
      - ai_system:/tmp
    depends_on:
      - activationBase
      - knowledgeBase
    command: 
      - sh
      - "-c"
      - |
        rm -rf /tmp/codeBase/ && cp -r /codeBase/ /tmp/;
        python /tmp/codeBase/ols_solution/apply_ols_model.py "/tmp/codeBase/ols_solution/result/" "/tmp/knowledgeBase/currentOlsSolution.pkl" "/tmp/activationBase/activation_data.csv";
        echo "The result is -->"
        cat /tmp/codeBase/ols_solution/result/ols_result.txt

volumes:
  ai_system:
    external: true
