FROM busybox

# data
ADD ../../data/train/train_data.csv /tmp/learningBase/train/
ADD ../../data/validate/test_data.csv /tmp/learningBase/validation/

# License & Readme
ADD ./Readme.md /tmp/learningBase/