FROM busybox

# OLS and AI models
ADD currentOlsSolution.pkl /knowledgeBase/currentOlsSolution.pkl
ADD currentAiSolution.h5 /knowledgeBase/currentAiSolution.h5

# License & readme
ADD README.md /tmp/knowledgeBase/
